version: '2.1'

services:
  mai-db-node-ex02:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: mai-db-node-ex02
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: stud
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    volumes:
      - db-node-ex02-data:/var/lib/mysql

  my_service:
    build:
      context: my_service
      dockerfile: Dockerfile
    container_name: my_service
    environment:
      - DB_HOST=mai-db-node-ex02
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex02:
        condition: service_healthy

  message_server:
    build:
      context: message_server
      dockerfile: Dockerfile
    container_name: message_server
    environment:
      - DB_HOST=mai-db-node-ex02
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SERVICE_HOST=my_service
    ports:
      - 8081:8081
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex02:
        condition: service_healthy

  wall_server:
    build:
      context: wall_server
      dockerfile: Dockerfile
    container_name: wall_server
    environment:
      - DB_HOST=mai-db-node-ex02
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SERVICE_HOST=my_service
    ports:
      - 8082:8082
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex02:
        condition: service_healthy

volumes:
  db-node-ex02-data:

networks:
  arch-network:
    driver: "bridge"
    external: false