openapi: "3.0.0"
info:
    version: "1.0.0"
    title: "Messages API"
    description: Сервис сообщений чата
servers:
    - url: http://localhost:8081
      description: Сервер сообщений

paths:
   /message:   
    post:
        summary: Создание сообщения
        description: Метод создает новое сообщение и возвращает дату создания
        parameters:
            - name: sender_id
              in: query
              description: Идентификатор создателя сообщения
              required: true
              schema:
                  type: integer
            - name: receiver_id
              in: query
              description: Идентификатор получателя сообщения
              required: true
              schema:
                  type: integer
            - name: text_message
              in: query
              description: Содержание сообщения
              required: true
              schema:
                  type: string
        responses:
            "200":
                description: Ид сообщения
                content:
                 application/json:
                  schema:
                    type: integer            
            404:
             description: Ошибка посылки сообщения
             content:
                application/json:
                 schema:
                     $ref: '#/components/schemas/Error'
            500:
             description: Неожиданная ошибка
             content:
                application/json:
                 schema:
                    $ref: '#/components/schemas/Error'
    put:
        summary: Изменение сообщения
        description: Метод изменяет сообщение и возвращает дату изменения
        parameters:
            - name: sender_id
              in: query
              description: Идентификатор создателя сообщения
              required: true
              schema:
                  type: integer
            - name: receiver_id
              in: query
              description: Идентификатор получателя сообщения
              required: true
              schema:
                  type: integer
            - name: message_id
              in: query
              description: Идентификатор изменяемого сообщения
              required: true
              schema:
                  $ref: '#/components/schemas/message_id'                
            - name: text_message
              in: query
              description: Содержание сообщения
              required: true
              schema:
                  type: string
        responses:
            "200":
                description: Дата изменения сообщения
                content:
                 application/json:
                  schema:
                    type: string            
            404:
             description: Ошибка изменения сообщения
             content:
                application/json:
                 schema:
                     $ref: '#/components/schemas/Error'
            500:
             description: Неожиданная ошибка
             content:
                application/json:
                 schema:
                    $ref: '#/components/schemas/Error'

    delete:
        summary: Удаление сообщения
        description: Метод удаляет сообщение
        parameters:
            - name: message_id
              in: query
              description: Идентификатор изменяемого сообщения
              required: true
              schema:
                  $ref: '#/components/schemas/message_id'    
        responses:
            "200":
                description: Сообщение удалено
            404:
             description: Ошибка удаления сообщения
             content:
                application/json:
                 schema:
                     $ref: '#/components/schemas/Error'
            500:
             description: Неожиданная ошибка
             content:
                application/json:
                 schema:
                    $ref: '#/components/schemas/Error'
    get:
        summary: Получение списка сообщений для пользователя
        description: Метод возвращает массив сообщений для указанного пользователя
        parameters:
            - name: sender_id
              in: query
              description: Идентификатор создателя сообщения
              required: true
              schema:
                  type: integer
            - name: receiver_id
              in: query
              description: Идентификатор получателя сообщения
              required: false
              schema:
                  type: integer
            - name: date_search
              in: query
              description: Дата поиска сообщений
              required: false
              schema:
                  type: string
        responses:
            "200": 
                description: Переписка получена
                content:
                 application/json:
                  schema:
                    $ref: '#/components/schemas/messages'
            404:
             description: Ошибка получения переписки
             content:
                application/json:
                 schema:
                     $ref: '#/components/schemas/Error'
            500:
             description: Неожиданная ошибка
             content:
                application/json:
                 schema:
                    $ref: '#/components/schemas/Error'
components:
    schemas:
        message_id:
            type: integer
            description: Уникальный Идентификатор сообщения        
        messages:
            type: array
            items:
                $ref: "#/components/schemas/message"
        message:
            type: object
            required:
                - id
                - sender_id
                - receiver_id
                - text_message
                - date_message
            properties:
             id:
                 $ref: '#/components/schemas/message_id'   
             sender_id:
                 type: integer
             receiver_id:
                 type: integer
             text_message:
                 type: string
             date_message:
                 type: string
        Error:
            type: object
            required:
                - message_error
            properties:
                message_error:
                    description: Сообщение о ошибке
                    type: string
    securitySchemes:
        basicAuth:
            type: http
            scheme: basic
security:
    - basicAuth: []

